### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by larseen** [larseen/tdt4300-project#5]
How did you solve the import error? 

example:

```
Traceback (most recent call last):
  File "/Users/Larsen/Documents/tdt4300-project/task1/121.py", line 3, in <module>
    from pyspark import  SparkContext
ImportError: No module named pyspark
```

**Comment by olavbm** [comment]
The lines in by .bashrc that has anytning todo with spark are the lines below. Change the paths to your respective folders tho.

export SPARK_HOME=/home/spark/spark-1.6.0-bin-hadoop2.6
export PYTHONPATH=$SPARK_HOME/python/
export PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.9-src.zip:$PYTHONPATH
export IPYTHON=1

also have spark in your path-variable.
